apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vegetation-module-ingress
  namespace: nekazari
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: nekazari.robotika.cloud
    http:
      paths:
      - path: /vegetation-prime
        pathType: Prefix
        backend:
          service:
            name: vegetation-prime-api-service
            port:
              number: 8000
  tls:
  - hosts:
    - nekazari.robotika.cloud
    secretName: nekazari-tls
